version: "3.7"
services:

  # Snapshot hub
  snapshot-hub:
    build: .
    container_name: snapshot-hub
    env_file:
      - .env.local
    depends_on:
      - snapshot-mysql
    ports:
      - "3001:3001"

  # Snapshot MySQL instance
  snapshot-mysql:  
    image: mariadb:10.6
    container_name: snapshot-mysql
    environment:
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "snapshot"
    volumes:
        - ./server/helpers/database/:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
      - "33060:33060"
 
networks:
  default:
    name: snapshot-network
