version: "3.7"
services:

  # Snapshot hub
  snapshot-hub:
    build: .
    container_name: snapshot-hub
    env_file:
      - .env
    environment:
      DATABASE_URL: mysql://admin:pwd@snapshot-mysql:3306/snapshot
    
    depends_on:
      - snapshot-mysql
    ports:
      - "3000:3000"

  # Snapshot MySQL instance
  snapshot-mysql:
    image: mysql:5.7
    container_name: snapshot-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "pwd"
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "snapshot"
    volumes:
        - "./src/helpers/database/:/docker-entrypoint-initdb.d/"

networks:
  default:
    name: snapshot-network
