scalar Object

type Space {
  id: String!
  name: String!
  network: String!
  private: Boolean
  members: [String]
  about: String
  twitter: String
  github: String
}

type User {
  address: String!
  profile: Profile
}

type Profile {
  ens: String
  name: String
  image: String
}

type TimelineProposal {
  id: String!
  author: User!
  timestamp: Int!
  space: Space!
  name: String!
  body: String!
  state: String!
  start: Int!
  end: Int!
  choices: [String]!
  snapshot: String!
}

type Query {
  timeline(
    first: Int
    skip: Int
    id: String
    spaces: [String]
    state: String
    orderBy: String
    orderDirection: OrderDirection
  ): [TimelineProposal]

  proposal(
    id: String
  ): Proposal

  proposals(
    first: Int
    skip: Int
    where: ProposalWhere,
    orderBy: String
    orderDirection: OrderDirection
  ): [Proposal]
}

type Proposal {
  id: String!
  author: String!
  created: Int!
  space: Space
  network: String!
  strategies: [Strategy]!
  plugins: Object!
  title: String!
  body: String
  choices: [String]!
  start: Int!
  end: Int!
  snapshot: String
  state: String
}

type Strategy {
  name: String!
  params: Object
}

input ProposalWhere {
  id: String
  id_in: [String]
  space: String
  space_in: [String]
  state: String
}

enum OrderDirection {
  asc
  desc
}
