name: Create a Sentry release
on:
  push:
    branches:
      - 'master'
jobs:
  create-sentry-release:
    strategy:
      matrix:
        target: ['24.14']
    uses: snapshot-labs/actions/.github/workflows/create-sentry-release.yml@feat/bun-support
    with:
      project: snapshot-hub
      target: ${{ matrix.target }}
      package_manager: bun
    secrets: inherit
