name: Create a Sentry release
on:
  push:
    branches:
      - 'master'
jobs:
  create-sentry-release:
    strategy:
      matrix:
        target: ['22.22']
    uses: snapshot-labs/actions/.github/workflows/create-sentry-release.yml@main
    with:
      project: snapshot-hub
      target: ${{ matrix.target }}
    secrets: inherit
