name: Lint

on: [push]

jobs:
  lint:
    strategy:
      matrix:
        target: ['24.14']
    uses: snapshot-labs/actions/.github/workflows/lint.yml@feat/bun-support
    secrets: inherit
    with:
      target: ${{ matrix.target }}
      package_manager: bun
