name: Test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        target: ['24.14']
    uses: snapshot-labs/actions/.github/workflows/test.yml@feat/bun-support
    secrets: inherit
    with:
      mysql_database_name: hub_test
      target: ${{ matrix.target }}
      package_manager: bun
